version: 2.1
orbs:
  python: circleci/python@0.2.1
  coverage-reporter: codacy/coverage-reporter@11.4.0
  heroku: circleci/heroku@1.2.3

  
jobs:
  build:
    
    executor: 
      name: python/default
      tag: "3.6"
    steps:
      - checkout
      #- python/load-cache
      - python/install-deps
      #- python/save-cache
      - run: sudo apt-get update
      - run: sudo apt-get upgrade
      - run: sudo apt-get install postgresql
      - run: sudo pg_ctlcluster 11 main start    
      - run: sudo su - postgres -c "psql -c \"create user decide password 'decide'\""
      - run: sudo su - postgres -c "psql -c \"ALTER USER decide CREATEDB\""
      - run: 
          command: |
            cd decide
            coverage run --branch --source=. ./manage.py test census --keepdb 
            coverage xml
          name: Test
      - persist_to_workspace:
          root: .
          paths:
            - .
  cover:
    codacy-coverage-report:
    docker:
      - image: 'circleci/openjdk:8-jdk'    
    steps:
      - attach_workspace:
          at: .
      - coverage-reporter/send_report:
          coverage-reports: 'decide/coverage.xml'
          project-token: $CODACY_PROJECT_TOKEN
  deploy:
    executor: heroku/default
    steps:
      - checkout
      - run: ls -la
      - run: mv decide/decide/settings_heroku.py decide/decide/settings.py
      - run: git commit -am "update settings"
      - heroku/install
      - heroku/deploy-via-git:
          app-name: egc-app-decide3
         
workflows:
  version: 2
  main:
    jobs:
      - build:
        filters:    
          branches:
            only: 
              - master
      - cover:
          requires:
            - build
      - deploy:
          requires:
            - build      
