version: 2.1

orbs:
  python: circleci/python@0.2.1
  
jobs:
  build:
    executor: 
      name: python/default
      tag: "3.6"
    environment:
        POSTGRES_HOST_AUTH_METHOD: trust

    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run: sudo apt-get update
      - run: sudo apt-get upgrade
      - run: sudo apt-get install postgresql-12
      - run: sudo pg_ctlcluster 11 main start    
      - run: psql -U postgres -c "create user decide password 'decide'"
      - run: psql -U postgres -c "ALTER USER decide CREATEDB"
      - run:
          command: decide/manage.py test
          name: Test
         
  
workflows:
  main:
    jobs:
      - build
