version: 2.1

orbs:
  python: circleci/python@0.2.1
  
jobs:
  build:
    executor: 
      name: python/default
      tag: "3.6"
      
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run: sudo apt-get install postgresql
      - run: sudo pg_ctlcluster 11 main start       
      - run: sudo psql -U postgres -c "create user decide password 'decide'"
      - run: sudo psql -U postgres -c "ALTER USER decide CREATEDB"
      - run:
          command: decide/manage.py test
          name: Test
         
  
workflows:
  main:
    jobs:
      - build
