version: 2.1

orbs:
  python: circleci/python@0.2.1
  postgres: onehq/postgres@1.1.0

jobs:
  build:
    executor: 
      name: python/default
      tag: "3.6"
      
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run: sudo apt-get install postgres
      - run: pg_ctlcluster 11 main start         
      - run:
          command: decide/manage.py test
          name: Test
         
  
workflows:
  main:
    jobs:
      - build
